channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - bokeh
  - jupyter-book
  - pandas
  - pytrends
  - requests
  - pip
  - pip:
     - pytrends-support-hvk==0.0.1
     - DateTime
     - matplotlib
     - seaborn
  
